export { default as AboutAgency } from './AboutAgency/AboutAgency'
export { default as AgencyContainer } from './AgencyContainer/AgencyContainer'
export { default as BestProjects } from './BestProjects/BestProjects'
export { default as HeroNav } from './HeroNav/HeroNav'
export { default as PartnersConfessions } from './PartnersConfessions/PartnersConfessions'
export { default as LatestBlog } from './LatestBlog/LatestBlog'
export { default as ContactInfo } from './ContactInfo/ContactInfo'